name: 'SendGrid sync'
description: 'Sync local handlebars with SendGrid'
author: 'nanopx'
inputs:
  sendgridApiKey:
    required: true
    description: 'SendGrid API Key'
  templatesDir:
    required: true
    description: 'Templates directory'
  partialsDir:
    required: false
    description: 'Partials directory'
  preserveVersions:
    required: false
    description: 'Number of versions to preserve per template'
    default: '2'
  dryRun:
    required: false
    description: 'Dry run'
runs:
  using: 'node12'
  main: 'dist/index.js'
