name: 'SendGrid sync'
description: 'Sync local handlebars with SendGrid'
author: 'nanopx'
inputs:
  sendgridApiKey:
    required: true
    description: 'SendGrid API Key'
  templatesDir:
    required: true
    description: 'Templates directory'
  partialsDir:
    required: false
    description: 'Partials directory'
runs:
  using: 'node12'
  main: 'dist/index.js'
