name: 'SendGrid sync'
description: 'Sync handlebars with SendGrid'
author: 'nanopx'
branding:
  color: red
  icon: refresh-cw
inputs:
  githubToken:
    required: true
    description: 'GitHub personal access token'
  sendgridApiKey:
    required: true
    description: 'SendGrid API Key'
  templatesDir:
    required: true
    description: 'Templates directory'
  partialsDir:
    required: false
    description: 'Partials directory'
  templatePrefix:
    required: false
    description: 'Template name prefixes'
    default: ''
  subjectTemplate:
    required: false
    description: 'Subject template'
    default: '{{subject}}'
  preserveVersions:
    required: false
    description: 'Number of versions to preserve per template'
    default: '2'
  outputFile:
    required: false
    description: 'Output file path for the mapping json'
  dryRun:
    required: false
    description: 'Dry run'
  forceSyncAll:
    required: false
    description: 'Force sync all files in templates dir (Useful for initial synchronization)'
outputs:
  sendgridTemplateIdMapping:
    description: JSON string which contains a mapping of template name(key) and template id(value)
runs:
  using: 'node12'
  main: 'dist/index.js'
